# Generated by Django 4.1.3 on 2022-11-25 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='alter',
            new_name='auction',
        ),
        migrations.RemoveField(
            model_name='alter',
            name='deadLine',
        ),
        migrations.AddField(
            model_name='alter',
            name='consigner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alter',
            name='underManagement',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startAmount', models.IntegerField()),
                ('minimumIncrement', models.IntegerField()),
                ('launchTime', models.DateTimeField()),
                ('deadLine', models.DateTimeField()),
                ('alter', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.alter')),
            ],
        ),
    ]
