# Generated by Django 4.1.2 on 2022-12-09 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_rename_alter_bid_auction_remove_alter_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction'),
        ),
        migrations.CreateModel(
            name='Alter_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.BinaryField(default=b'\x00', editable=True)),
                ('alter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.alter')),
            ],
        ),
    ]
