# Generated by Django 4.1.1 on 2022-10-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='customer_id',
            field=models.SlugField(default='010101010101', max_length=64),
            preserve_default=False,
        ),
    ]
